### ISSUE TITLE
Could not find package

### ISSUE THREAD

**Issue by Maykonn** [yiisoft/yii2-maskedinput#1]
### What steps will reproduce the problem?
Try composer require --prefer-dist yiisoft/yii2-maskedinput

### What's expected?
Package be installed

### What do you get instead?
```
[InvalidArgumentException]                                                                                                                                
  Could not find package yiisoft/yii2-maskedinput at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

### Additional info

```
"minimum-stability": "stable",
```

| Q                | A
| ---------------- | ---
| Yii vesion      | 2
| PHP version    | 5.6
| Operating system | OSx

**Comment by samdark** [comment]
It wasn't released yet. Are you using Yii 2.1?

**Comment by Maykonn** [comment]
My version is 2.0.11.2.

**Comment by samdark** [comment]
Then you already have this class. It is in 2.0 core.

**Comment by Maykonn** [comment]
Thank you!
