### ISSUE TITLE
Question: Why is this widget in a separate repository?

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2-maskedinput#2]
Is not it part of yii2 core widgets?

**Comment by samdark** [comment]
It is for Yii 2.1.

**Comment by santilin** [comment]
Ok, I just wanted to point out that in the documentation sample, the mask value for the date field, "999-999-9999" does  not make any sense. It should be a valid mask, like "9999/99/99".

**Comment by samdark** [comment]
Yes. Feel free to create a pull request. We're going to get back to this repository when Yii 2.1 is close but I'll merge these changes.
